settings:
  path: M:\tactip-time-series-data         # temp/tactile_data
  seed: 42                     # for repeatable random numbers
  overwrite_on: true           # Overwrite existing data
  restore_on: true             # Restore original data from backup before processing
  device: cpu                  # Device to use: cpu or cuda

globals:
  IMAGE: time_series_images
  OBJECT_CLASS: class
  OBJECT_POSE: [object_x, object_y, object_z, object_Rx, object_Ry, object_Rz]
  POSE: [pose_x, pose_y, pose_z, pose_Rx, pose_Ry, pose_Rz]
  SHEAR: [shear_x, shear_y, shear_z, shear_Rx, shear_Ry, shear_Rz]
  SPEED: [linear_speed, angular_speed]


collect:
  name: surface-z-Silvia
  sample_nums: 10
  experiment: ${collect.robot}/${sensor.name}/${collect.name}
  robot: ur5
  ip: 192.168.6.6
  # pose_lims: [[0, 0, 5, -20, -20, -45], [0, 0, 5, 20, 20, 45]]

  pose_lims: [[0, 0, 3, -15, -15, 0], [0, 0, 5, 15, 15, 0]]
  shear_lims: [[-15, -15, 0, 0, 0, -20], [15, 15, 0, 0, 0, 20]]
  speed_lims: [[10, 15],[30, 45]] # linear, angular
  sort_on: true 
  real:
    # SoftRobot Group UR5  base height including ft sensor 62.5mm
    # tactip sensor 20mm (dome radius) + 82mm
    tcp_pose: [0, 0, -82, 0, 0, 0] 
    work_frame: [-500, -65, 82.5, 180, 0, 0]  # UR5 Test -- z 164.5mm on teachpendant
    # work_frame: [240, 0, 0, -180, 0, 0]   # mg400 Test
    free_speed: 50

sensor:
  name: tactip-Silvia
  camera:
    source: 2
    exposure: 10
    width: 1920 # 1920 # 640 # 1024 # 1280
    height: 1080 # 1080 # 480 # 768 # 960
    fps: 120.0

  process_images: null
    # visualise_on: true
    # crop: [988, 509, 560]
    # # circle_mask_radius: 560
    # single_channel: blue
    # led_masks: [[36, 400, 15], [155, 939, 15], [688, 1096, 15], [1088, 721, 15], [965, 184, 15], [440, 42, 15]]

  process_markers:
    visualise_on: false
    num_markers: 127
    num_rings: 7
    backbone_offset_deg: 30

    detector_type: CVConnectedComponent
    image_scale: 1
    detector_kwargs:
      morphology_ksize: 5
      size_filter: [0.5, 2]
      binary_threshold: [83, -21]



ft_sensor:
  ip: 192.168.1.1
  port: 49152

sync:
  sync_slop: 0.01
  queue_size: 10