name: simple_gnn
n_epochs: 100

kwargs:
  conv_layers: [16, 32, 48, 64, 96]
  fc_layers: [128, 96]
  activation: leaky_relu
  dropout: 0.0
  apply_batchnorm: True

loader:
  batch_size: 128
  shuffle: true
  num_workers: 0

optimizer:
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0.000001

scheduler: ReduceLROnPlateau
lr_scheduler:
  factor: 0.5
  patience: 3

preprocess:
  data_type: nodes # nodes areas nodes_areas
  num_markers: ${sensor.process_markers.num_markers}
