# @package _global_

defaults:
  - /runtime/base
  - /collect: surface_zRxy_ur # surface_z_ur_Silvia
  - _self_

settings:
  seed: 42 

collect:
  name: surface-zRxy-June19-classic
  sample_nums: 2000
  experiment: ${collect.robot}/${sensor.name}/${collect.name}
  ip: 192.168.1.164
  fixed_speed: true
  classic_data: true
  pose_lims: [[0, 0, 0.5, -20, -20, 0], [0, 0, 4, 20, 20, 0]]
  shear_lims: [[-5, -5, 0, 0, 0, -10], [5, 5, 0, 0, 0, 10]]
  speed_lims: [[30, 45], [30, 45]]
  free_speed: 100
  sort_on: true

sensor:
  name: tactip-127
  camera:
    camera_name: /dev/video0 # /dev/video0 # video=HD USB Camera
    exposure: 10
    width: 1920 # 1920 # 640 # 1024 # 1280
    height: 1080 # 1080 # 480 # 768 # 960
    fps: 120.0
    writer_workers: 8 # Concurrent image writers (increase carefully)
    png_compression: 1
    storage_format: zip # png # zip
  process_images:
    single_channel: blue

ft_sensor:
  ip: 192.168.1.187 # 192.168.1.1
  port: 49152
